# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    VERSION_TUPLE = Tuple[int | str, ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = '0.1.dev307+g921988f.d20240922'
__version_tuple__ = version_tuple = (0, 1, 'dev307', 'g921988f.d20240922')
